<?php

return [
    'name' => env('HOTEL_NAME', 'Maculusso Hotel'),
    'booking_url' => env('HOTEL_BOOKING_URL', 'https://www.booking.com/'),
    'phone' => env('HOTEL_PHONE', '+244 923 000 000'),
    'phone_link' => env('HOTEL_PHONE_LINK', '+244923000000'),
    'whatsapp' => env('HOTEL_WHATSAPP', 'https://wa.me/244923000000'),
    'email' => env('HOTEL_EMAIL', 'reservas@hotelmaculusso.com'),
    'address' => env('HOTEL_ADDRESS', 'Bairro Maculusso, Luanda, Angola'),
    'city' => 'Luanda',
    'social' => [
        'instagram' => env('HOTEL_INSTAGRAM', 'https://instagram.com/'),
        'facebook' => env('HOTEL_FACEBOOK', 'https://facebook.com/'),
    ],

    // Room types. Prices in AOA (Kwanza) per night — adjust freely here.
    'rooms' => [
        [
            'slug' => 'executive',
            'name' => 'Executive',
            'tagline' => 'Conforto para quem trabalha',
            'price' => 115500,
            'price_double' => 128500,
            'max_guests' => 2,
            'detail' => '2 hóspedes · 26 m² · Cama queen',
            'guests' => '2 hóspedes',
            'size' => '26 m²',
            'bed' => 'Cama queen',
            'image' => 'https://images.unsplash.com/photo-1595576508898-0ad5c879a061?auto=format&fit=crop&w=1400&q=85',
            'description' => 'Quarto executivo com todas as comodidades essenciais para uma estadia confortável e produtiva no coração de Luanda.',
            'amenities' => ['Ar condicionado', 'Wi-Fi de alta velocidade', 'Smart TV', 'Zona de trabalho', 'Cofre'],
        ],
        [
            'slug' => 'premium',
            'name' => 'Premium',
            'tagline' => 'Acabamentos superiores',
            'price' => 118800,
            'price_double' => 131800,
            'max_guests' => 2,
            'detail' => '2 hóspedes · 30 m² · Cama queen',
            'guests' => '2 hóspedes',
            'size' => '30 m²',
            'bed' => 'Cama queen',
            'image' => 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1400&q=85',
            'description' => 'Quarto premium com acabamentos superiores e vista privilegiada para o hotel. O equilíbrio perfeito entre espaço e aconchego.',
            'amenities' => ['Ar condicionado', 'Wi-Fi de alta velocidade', 'Smart TV', 'Minibar', 'Cofre'],
        ],
        [
            'slug' => 'premium-pool',
            'name' => 'Premium Pool',
            'tagline' => 'Acesso directo à piscina',
            'price' => 122100,
            'price_double' => 135100,
            'max_guests' => 2,
            'detail' => '2 hóspedes · 30 m² · Cama queen',
            'guests' => '2 hóspedes',
            'size' => '30 m²',
            'bed' => 'Cama queen',
            'image' => 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1400&q=85',
            'description' => 'Quarto premium com acesso directo à piscina e vistas deslumbrantes. Ideal para começar e terminar o dia ao seu ritmo.',
            'amenities' => ['Ar condicionado', 'Wi-Fi de alta velocidade', 'Smart TV', 'Minibar', 'Acesso à piscina', 'Cofre'],
        ],
        [
            'slug' => 'suite-executive-kitchenette',
            'name' => 'Suite Executive Kitchenette',
            'tagline' => 'Pensada para estadias longas',
            'price' => 165000,
            'price_double' => 178000,
            'max_guests' => 3,
            'detail' => '3 hóspedes · 38 m² · Kitchenette',
            'guests' => '3 hóspedes',
            'size' => '38 m²',
            'bed' => 'Cama king',
            'image' => 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1400&q=85',
            'description' => 'Suite executiva com kitchenette totalmente equipada para estadias prolongadas, com zona de estar independente e todo o conforto de casa.',
            'amenities' => ['Ar condicionado', 'Wi-Fi de alta velocidade', 'Smart TV', 'Kitchenette equipada', 'Minibar', 'Cofre'],
        ],
        [
            'slug' => 'suite-premium-kitchenette',
            'name' => 'Suite Premium Kitchenette',
            'tagline' => 'Espaços amplos, máximo conforto',
            'price' => 176000,
            'price_double' => 189000,
            'max_guests' => 3,
            'detail' => '3 hóspedes · 46 m² · Kitchenette',
            'guests' => '3 hóspedes',
            'size' => '46 m²',
            'bed' => 'Cama king',
            'image' => 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1400&q=85',
            'description' => 'Suite premium com kitchenette e espaços amplos para máximo conforto. Uma escolha natural para quem fica mais tempo em Luanda.',
            'amenities' => ['Ar condicionado', 'Wi-Fi de alta velocidade', 'Smart TV', 'Kitchenette equipada', 'Minibar', 'Zona de estar', 'Cofre'],
        ],
        [
            'slug' => 'suite-master-kitchenette',
            'name' => 'Suite Master Kitchenette',
            'tagline' => 'O nosso espaço mais generoso',
            'price' => 187000,
            'price_double' => 200000,
            'max_guests' => 4,
            'detail' => '4 hóspedes · 58 m² · Kitchenette',
            'guests' => '4 hóspedes',
            'size' => '58 m²',
            'bed' => 'Cama king + sofá-cama',
            'image' => 'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=1400&q=85',
            'description' => 'A nossa suite mais ampla, com kitchenette completa, sala de estar e espaço para toda a família. Elegância e privacidade sem compromissos.',
            'amenities' => ['Ar condicionado', 'Wi-Fi de alta velocidade', 'Smart TV', 'Kitchenette equipada', 'Sala de estar', 'Minibar', 'Cofre'],
        ],
    ],

    // Service categories — the hotel's own offering.
    'services' => [
        ['title' => 'Cocktail Bar', 'body' => 'Uma selecção exclusiva de bebidas, dos cocktails clássicos a criações da casa, preparados pelos nossos bartenders num lounge sofisticado.'],
        ['title' => 'Gastronomia', 'body' => 'Uma experiência culinária única. O nosso restaurante serve pratos preparados com ingredientes frescos e de alta qualidade, com identidade angolana e internacional.'],
        ['title' => 'Lazer', 'body' => 'Piscina, ginásio e espaços para relaxar. No Maculusso, o lazer é levado a sério para que a sua estadia seja tão descansada quanto produtiva.'],
        ['title' => 'Serviços Personalizados', 'body' => 'Cada hóspede é único. A nossa equipa está sempre pronta para antecipar necessidades e garantir que a sua estadia decorre exactamente como imagina.'],
    ],
];
